spring.datasource.url=jdbc:h2:file:./CA2-Part2/PayrollDB
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:h2:tcp://192.168.56.11:9092//home/vagrant/PayrollDB
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.hibernate.ddl-auto=update