pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'gradlew.bat bootRun'
            }
        }

        stage('Test') {
            steps {
                bat 'gradlew.bat test'
                junit 'build/test-results/test/*.xml'
            }
        }

        stage('Deploy') {
            steps {
                bat 'gradlew.bat publish'
            }
        }
    }
}