pipeline {
    agent { label 'linux'}
    stages {
        stage('Checkout') {
            steps {
                echo "Pulling source code..."

                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/pchu22/COGSI2526_1250503_1250506_1250545-copy']],
                    gitTool: isUnix() ? 'DefaultLinuxGit' : 'DefaultWindowsGit'
                ])
            }
        }

        stage('Assemble') {
            steps {
                echo "Building project..."

                dir('CA2/PART-II/gradle-tut-rest') {
                    script {
                        if (isUnix()) {
                            sh './gradlew clean build'
                        }
                        else {
                            bat 'gradlew.bat clean build'
                        }
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo "Running test..."

                dir('CA2/PART-II/gradle-tut-rest') {
                    script {
                        if (isUnix()) {
                            sh './gradlew test'
                        } else {
                            bat 'gradlew.bat test'
                        }
                    }
                    junit 'build/test-results/test/*.xml'
                }
            }
        }

         stage('Archiving') {
            steps {
                echo 'Archiving artifacts...'

                archiveArtifacts 'CA2/PART-II/gradle-tut-rest/build/libs/*.jar'
            }
         }


         stage('Deploy to Production') {
            steps {
                echo "Deploying to production..."

                script {
                    timeout(time: 60, unit: 'SECONDS') {
                        input(message: 'Deploy application to PRODUCTION?', ok: 'Approve Deployment')
                    }
                }

                script {
                    if (isUnix()){
                        sh """
                            ansible-playbook -i playbook-green.yaml
                        """
                    } else {
                        powershell """
                            wsl ansible-playbook -i playbook-green.yaml
                        """
                    }
                }
            }
         }
    }

    post {
        success {
            echo "Build succeeded!"
        }

        failure {
            echo "Build failed!"
        }
    }
}