Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"

    config.ssh.forward_agent = true
    config.ssh.insert_key = false

    config.vm.define "blue" do |blue|

        blue.vm.provider "virtualbox" do |vb|
            vb.name = "blue"
            vb.memory = 1024
            vb.cpus = 2
        end

        blue.vm.network "private_network", ip: "192.168.56.10"
        blue.vm.network "forwarded_port", guest: 8080, host: 8081

        blue.vm.provision "ansible" do |ansible|
            ansible.playbook = "./playbook.yaml"
            ansible.compatibility_mode = "2.0"
        end
    end

    config.vm.define "green" do |green|

        green.vm.provider "virtualbox" do |vb|
            vb.name = "green"
            vb.memory = 1024
            vb.cpus = 2
        end

        green.vm.network "private_network", ip: "192.168.56.11"
        green.vm.network "forwarded_port", guest: 8080, host: 8083

        green.vm.provision "ansible" do |ansible|
            ansible.playbook = "./playbook-green.yaml"
            ansible.compatibility_mode = "2.0"
        end
    end
end
