Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "ca6-p2"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ca6-p2"
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.network "private_network", ip: "192.168.56.12"
  config.vm.network "forwarded_port", guest: 8080, host: 8085

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end