Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"

    config.ssh.forward_agent = true
    config.ssh.insert_key = false

    config.vm.define "web-app" do |web|

        web.vm.provider "virtualbox" do |vb|
            vb.name = "web-app"
            vb.memory = 1024
            vb.cpus = 2
        end

        web.vm.network "private_network", ip: "192.168.56.10"
        web.vm.network "forwarded_port", guest: 8080, host: 8080

        web.vm.provision "ansible" do |ansible|
            ansible.playbook = "./playbook.yaml"
            ansible.compatibility_mode = "2.0"
        end
    end

    config.vm.define "db-server" do |db|

        db.vm.provider "virtualbox" do |vb|
            vb.name = "db-server"
            vb.memory = 1024
            vb.cpus = 2
        end

        db.vm.network "private_network", ip: "192.168.56.11"

#         db.vm.provision "file", source: "/mnt/c/Users/pmdc2/.gradle/caches/modules-2/files-2.1/com.h2database/h2/2.3.232/4fcc05d966ccdb2812ae8b9a718f69226c0cf4e2/h2-2.3.232.jar", destination: "/home/vagrant/libs/h2-2.3.232.jar"
        db.vm.provision "file", source: "/mnt/c/MCS/COGSI/CA2/PART-II/gradle-tut-rest/CA2-Part2/PayrollDB.mv.db", destination: "/home/vagrant/"
        db.vm.provision "ansible" do |ansible|
            ansible.playbook = "./playbook.yaml"
            ansible.compatibility_mode = "2.0"
        end
    end
end
